"""
The locked recipe for every Marlowe scene.

    python scene.py "<scene sentence>" "<composition sentence>"

Prints the exact prompt and the two reference ids to pass to Higgsfield.

WHY THIS FILE EXISTS
--------------------
Twice on this project a scene was generated by passing a PREVIOUSLY GENERATED
SCENE as the second reference, because that output looked like a good example
of the target. Both times the result drifted: the wet-ink outline thinned, the
glasses shrank, and the mustache and whiskers disappeared, so the cat read as a
cleaner, different character. Referencing an output chains the drift; every hop
away from the masters compounds it.

So the masters are constants here, not arguments. There is no parameter that
lets a caller substitute a different reference, and the prompt is assembled
from a frozen template where only two sentences vary. If a new scene needs
something the template cannot express, change the template deliberately and
regenerate the existing four locations against it, rather than special-casing
one scene.
"""
import sys

# The only two references any Marlowe generation may use, ever.
INK_MASTER = "848fef5c-e479-49f2-918f-9308a9a53f9e"    # linework and texture
OUTFIT_MASTER = "cc4c0db0-715a-4f07-bc9d-74bbc0cd0c61"  # character and sweater
REFERENCES = [INK_MASTER, OUTFIT_MASTER]

MODEL = "nano_banana_2"   # resolves server-side to nano_banana_flash
ASPECT = "1:1"

# Frozen. Only {scene} and {composition} are ever substituted. Everything else
# is byte-identical to the prompt that produced the approved desk and armchair.
TEMPLATE = """A single cat character in a small scene, drawn in the EXACT style of the attached references. Keep the thick heavy wet-ink bleeding black outline, the rough grainy brush edges and the flat matte fills exactly as in the first reference image.

THE CHARACTER: white wedge head with tall pointed black-outlined ears, two solid black dot eyes, small round black wire glasses, thick black squiggle mouth, thick black whisker strokes, warm MUSTARD OCHRE knit turtleneck sweater with a ribbed rolled collar, two blocky black mitten paws.

THE SCENE: {scene}

COMPOSITION IS CRITICAL: the CAT must be LARGE and DOMINANT, filling most of the height of the square frame. {composition} Nothing else in the picture.

FLAT PLAIN NEUTRAL GREY background, no texture, no pattern. Generous margin, nothing cropped at the frame edges. Completely flat even lighting, no cast shadows, no ground shadow. No text, no watermark."""


def prompt(scene: str, composition: str) -> str:
    return TEMPLATE.format(scene=scene.strip(), composition=composition.strip())


# The approved still for each location, i.e. the image the three cycle videos
# were rendered from. Recorded so a cycle can be re-shot without re-rolling the
# drawing, and so it is obvious which generation is the blessed one.
#
# NOTE these are OUTPUTS. They are start_image inputs to generate_video only.
# They must never be passed as a reference to generate_image; see the module
# docstring for what that costs.
APPROVED = {
    "desk": "3a3ebb3c-3a65-4433-a8d3-9d53bcf05af0",
    "armchair": "873cce60-e58e-4a99-929a-960327110d31",
    "window": "c3a86b1d-595d-4fe7-9651-ef3aced6d5ff",
    "hearth": "ef26c222-7e05-4aa4-8503-a307004276f2",
}

# How many attempts each approved still took, as a reminder that this is a
# selection process and not a prompt-wording one: desk 9, armchair 3, window 6,
# hearth 6. Generate a batch of 4 with `count`, then pick on the face at full
# size against assets/sprites/desk-12.png. Never judge from a thumbnail.

# The four shipped locations, kept here so any of them can be regenerated
# identically. Keys match `equipped.location` in lib/state.ts.
SCENES = {
    "desk": (
        "he sits at a PLAIN BROWN WOODEN WRITING DESK seen from a slight three-quarter angle. "
        "An open notebook lies flat on the desk in front of him and both of his blocky black "
        "mitten paws rest on the desk on either side of it. His head is tilted slightly down "
        "toward the notebook.",
        "The desk is a compact slab across the lower part of the frame, not a big wide room. "
        "No chair back, no lamp, no clutter.",
    ),
    "armchair": (
        "he is SITTING IN A DEEP RED ARMCHAIR with rounded padded arms, holding a notebook, "
        "both paws on the notebook as if writing. Immediately to his right stands a SHORT "
        "NARROW WOODEN BOOKSHELF, only about as tall as the chair back, holding a few coloured "
        "book spines.",
        "The armchair and the little bookshelf are compact and tucked close beside him, not a "
        "big wide room.",
    ),
    "window": (
        "he is SITTING ON A CUSHIONED WOODEN WINDOW SEAT, holding a notebook, both paws on the "
        "notebook as if writing. Immediately to his right stands a SMALL SQUARE WINDOW, only "
        "about as tall as his head, with a wooden frame and rain streaks on the glass.",
        "The window seat and the little window are compact and tucked close beside him, not a "
        "big wide room.",
    ),
    "hearth": (
        "he is SITTING ON A SMALL ROUND CUSHION, holding a notebook, both paws on the notebook "
        "as if writing. Immediately to his right stands a COMPACT BRICK FIREPLACE, only about "
        "as tall as he is, with an arched opening and a small orange fire burning inside it.",
        "The cushion and the little fireplace are compact and tucked close beside him, not a "
        "big wide room.",
    ),
}


def main():
    if len(sys.argv) == 2 and sys.argv[1] in SCENES:
        scene, composition = SCENES[sys.argv[1]]
    elif len(sys.argv) == 3:
        scene, composition = sys.argv[1], sys.argv[2]
    else:
        print(__doc__)
        print("known scenes:", ", ".join(SCENES))
        sys.exit(1)

    print("model:     ", MODEL)
    print("aspect:    ", ASPECT)
    print("references:", REFERENCES)
    print()
    print(prompt(scene, composition))


if __name__ == "__main__":
    main()
